version: "3.9"

services:
  fe-angular:
    build: .
    container_name: fe-angular
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
